name: msc-nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - matplotlib
  - boto3
  - pyarrow
  - pyyaml
  - extruct
  - htmldate
  - spacy
  - trafilatura
  - tldextract
  - warcio
  - py3langid
  - pytorch
  - transformers<5
  - tokenizers
  - safetensors
  - huggingface_hub>=0.34,<1
  - sentence-transformers
  - scikit-learn
  - tqdm
  - nbconvert
  - openpyxl
  - ruff
  - pip:
      - datatrove==0.9.0
      - pywb
      - resiliparse
